project:
  type: manuscript

notebook-links: false #not currently available to disable by format. Ideally we want links in HTML, not in doc/pdf.
 
execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
#  jats: default
  agu-pdf: default
  apaish-manuscript-typst: default
  apaish-document-typst: default
  apaish-journal-typst: default