project:
  type: manuscript

notebook-links: false #not currently available to disable by format. Ideally we want links in HTML, not in doc/pdf.
code-links: repo

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
#  jats: default
  # agu-pdf: default
# Note only one PDF or typst output can be specified at a time
  apaish-manuscript-typst: default # one column, double spaced for submission to a journal
  # apaish-document-typst: default # more formatted, LaTex style, still one column
  # apaish-journal-typst: default # two column, extra formatted, like you might use for a preprint
