---
title: A Super Cool Study 
author:
  - name: Josephine Student 
    orcid: 0000-0002-7859-8394
    corresponding: false
    roles: []
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
  - name: John J. Curtin 
    orcid: 0000-0002-3286-938X
    corresponding: true
    email: jjcurtin@wisc.edu
    roles:
      - Investigation
      - Project administration
      - Software
      - Visualization
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison 
keywords:
  - Substance use disorders
  - Precision mental health 
abstract: |
  This study found some pretty cool results that have both high impact and important clinical implications.  For example ...
plain-language-summary: |
  The ARC produces some of the best science around! ...
key-points:
  - Take away point 1 
  - Take away point 2
date: last-modified
bibliographystyle: apa
number-sections: false 
editor_options: 
  chunk_output_type: console
---

## Introduction {#sec-intro}

You can write your text using markdown.  

Top level section headings use ##

Notice use of curly braces to label a section if you want to later cross-reference to it.  #sec-  is required as part of the label


### Sub-heading Demo

You can use sub-headings in your paper as well



### References

We can use cite relevant research in multiple formats.  The two most common are: 

- @marrero2019 concluded something.  
- These are the conclusions[@marrero2019].

Article references are stored in a .bib file using betterbibtex (BBT) format.  We create these references in Zotero collections.

Although we don't do this regularly I think, if needed you can 

Issue with Typst breaking on ["unnumbered references"](https://github.com/typst/typst/issues/1142)

Change number-sections: in YAML to TRUE to fix this (although that causes unwanted numbering!)
<!-- - reference other sections in the paper (e.g., Methods are described in @sec-methods) -->
- reference figures elsewhere using the @ symbol.   Here is a reference to @fig-1


## Methods {#sec-methods}



## Results {#sec-results}

To add results that are not figures or tables, you will need to open the analysis objects you saved from these analyses.  See lm.qmd as an example. Generally you will open csv files that contain tidied results. For example

NOTES: 

- We should write a function that works with tidied coeffs tables and takes the row, column, and number of decimal  places to make this code simpler.
- This table doesnt contain df.  Need to add that to table when saving in lm


## Discussion {#sec-discussion}



<!-- Note: Ref section still doesn't seem APA style. Typst will in teh future support standalone refs. In the meantime, this works but ONLY in the typst APA output. You also have to comment out the bibliography: line in the YAML for it to work. -->

<!-- ```{=typst}  -->
<!-- #bibliography("references.bib", title: "References", style: "apa") -->
<!-- ``` -->


```{=typst} 
#bibliography("references.bib", title: "References", style: "apa")
```