---
title: "EMA study PR Curves"
author: "John Curtin"
editor_options: 
  chunk_output_type: console
---
## Set up environment
```{r}
# handle conflicts
options(conflicts.policy = "depends.ok")

library(tidyverse, quietly = TRUE)
theme_set(theme_classic()) 

# Paths
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true",
                     sha1 = "a58e57da996d1b70bb9a5b58241325d6fd78890f")
path_models <- format_path("studydata/risk/models/ema")
path_data_shared <- format_path("studydata/risk/data_processed/shared")
path_data_ema <- format_path("studydata/risk/data_processed/ema")
```

## Open preds dfs
```{r}
preds_week<- read_rds(file.path(path_models, 
                               "outer_preds_1week_0_v5_nested_main.rds"))
preds_day<- read_rds(file.path(path_models, 
                              "outer_preds_1day_0_v5_nested_main.rds"))
preds_hour<- read_rds(file.path(path_models, 
                               "outer_preds_1hour_0_v5_nested_main.rds"))
```

## Generate PR curves

```{r}
pr_week <- preds_week |> 
  yardstick::pr_curve(prob_beta, truth = label) |> 
  mutate(model = "1week")

pr_day <- preds_day |> 
  yardstick::pr_curve(prob_beta, truth = label) |> 
  mutate(model = "1day")

pr_hour <- preds_hour|> 
  yardstick::pr_curve(prob_beta, truth = label) |> 
  mutate(model = "1hour")

pr_all <- pr_week |> 
  bind_rows(pr_day) |> 
  bind_rows(pr_hour) |> 
  mutate(thres_avg = round(.threshold, 3)) |> 
  group_by(model, thres_avg) |> 
  reframe(recall = mean(recall), precision =  mean(precision)) |> 
  mutate(model = factor(model, levels = c("1week", "1day", "1hour"),
                        labels = c("week", "day", "hour")))
```

### Plot PR Curve

```{r}
#| label: fig-prcurve
#| fig-cap: PR Curves by Model
#| fig-height: 6
#| fig-width: 6

pr_all |>
  ggplot(aes(x = recall, y = precision, color = model)) +
  geom_path(size = 1.25) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "Sensitivity (Recall)",
       y = "Positive Predictive Value (Precision)") +
  scale_color_manual(values = c("orange","green","blue")) +
  geom_hline(yintercept = .70, color = "black", size = 1, linetype = "dotted") +
  geom_segment(x = .72, y = -.05 , xend = .72, yend = .70,
               color = "orange", size = 1, linetype = "dotted") +
  geom_segment(x = .47, y = -.05 , xend = .47, yend = .70,
               color = "green", size = 1, linetype = "dotted") +
  geom_segment(x = .33, y = -.05 , xend = .33, yend = .70,
               color = "blue", size = 1, linetype = "dotted")
```